//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apskaita5.DAL.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apskaita5.DAL.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for the role {0}:.
        /// </summary>
        internal static string ApplicationRoleSchema_DataErrorsHeader {
            get {
                return ResourceManager.GetString("ApplicationRoleSchema_DataErrorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot have blank spaces..
        /// </summary>
        internal static string ApplicationRoleSchema_RoleNameContainsBlankSpaces {
            get {
                return ResourceManager.GetString("ApplicationRoleSchema_RoleNameContainsBlankSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is not specified..
        /// </summary>
        internal static string ApplicationRoleSchema_RoleNameNull {
            get {
                return ResourceManager.GetString("ApplicationRoleSchema_RoleNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for application roles schemas:.
        /// </summary>
        internal static string ApplicationRoleSchemaList_DataErrorsHeader {
            get {
                return ResourceManager.GetString("ApplicationRoleSchemaList_DataErrorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema is not a child of the current list..
        /// </summary>
        internal static string ApplicationRoleSchemaList_SchemaIsNotChild {
            get {
                return ResourceManager.GetString("ApplicationRoleSchemaList_SchemaIsNotChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot autoincrement non integer value..
        /// </summary>
        internal static string DbFieldSchema_AutoincrementInvalid {
            get {
                return ResourceManager.GetString("DbFieldSchema_AutoincrementInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum values are not specified..
        /// </summary>
        internal static string DbFieldSchema_EnumValuesNull {
            get {
                return ResourceManager.GetString("DbFieldSchema_EnumValuesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least two enum values should be specified..
        /// </summary>
        internal static string DbFieldSchema_EnumValuesTooShort {
            get {
                return ResourceManager.GetString("DbFieldSchema_EnumValuesTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for field {0} {1}({2}):.
        /// </summary>
        internal static string DbFieldSchema_ErrorStringHeader {
            get {
                return ResourceManager.GetString("DbFieldSchema_ErrorStringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field length cannot be negative..
        /// </summary>
        internal static string DbFieldSchema_FieldLengthNegative {
            get {
                return ResourceManager.GetString("DbFieldSchema_FieldLengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name cannot have blank spaces..
        /// </summary>
        internal static string DbFieldSchema_FieldNameContainsBlankSpaces {
            get {
                return ResourceManager.GetString("DbFieldSchema_FieldNameContainsBlankSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is not specified..
        /// </summary>
        internal static string DbFieldSchema_FieldNameNull {
            get {
                return ResourceManager.GetString("DbFieldSchema_FieldNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index name is not specified..
        /// </summary>
        internal static string DbFieldSchema_IndexNameNull {
            get {
                return ResourceManager.GetString("DbFieldSchema_IndexNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced field is not specified..
        /// </summary>
        internal static string DbFieldSchema_RefFieldNull {
            get {
                return ResourceManager.GetString("DbFieldSchema_RefFieldNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced table is not specified..
        /// </summary>
        internal static string DbFieldSchema_RefTableNull {
            get {
                return ResourceManager.GetString("DbFieldSchema_RefTableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for database:.
        /// </summary>
        internal static string DbSchema_ErrorStringHeader {
            get {
                return ResourceManager.GetString("DbSchema_ErrorStringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for tables:.
        /// </summary>
        internal static string DbSchema_ErrorStringTablesHeader {
            get {
                return ResourceManager.GetString("DbSchema_ErrorStringTablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database has no tables..
        /// </summary>
        internal static string DbSchema_TableListEmpty {
            get {
                return ResourceManager.GetString("DbSchema_TableListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL statement could be empty..
        /// </summary>
        internal static string DbSchemaError_EmptySqlStatementInList {
            get {
                return ResourceManager.GetString("DbSchemaError_EmptySqlStatementInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for table {0} fields:.
        /// </summary>
        internal static string DbTableSchema_ErrorStringFieldsHeader {
            get {
                return ResourceManager.GetString("DbTableSchema_ErrorStringFieldsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors for table {0}:.
        /// </summary>
        internal static string DbTableSchema_ErrorStringHeader {
            get {
                return ResourceManager.GetString("DbTableSchema_ErrorStringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table has no fields..
        /// </summary>
        internal static string DbTableSchema_FieldListEmpty {
            get {
                return ResourceManager.GetString("DbTableSchema_FieldListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name cannot have blank spaces..
        /// </summary>
        internal static string DbTableSchema_TableNameContainsEmptySpaces {
            get {
                return ResourceManager.GetString("DbTableSchema_TableNameContainsEmptySpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name is not specified..
        /// </summary>
        internal static string DbTableSchema_TableNameNull {
            get {
                return ResourceManager.GetString("DbTableSchema_TableNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index value {0} was out of column list range..
        /// </summary>
        internal static string IndexValueOutOfRange {
            get {
                return ResourceManager.GetString("IndexValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names within a table should be unique..
        /// </summary>
        internal static string LightDataColumn_NameNotUnique {
            get {
                return ResourceManager.GetString("LightDataColumn_NameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns cannot be added to a readonly collection. (The collection is readonly when any row is added to the parent table.).
        /// </summary>
        internal static string LightDataColumnCollection_CannotAddColumnToReadOnlyCollection {
            get {
                return ResourceManager.GetString("LightDataColumnCollection_CannotAddColumnToReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns cannot be removed from a readonly collection. (The collection is readonly when any row is added to the parent table.).
        /// </summary>
        internal static string LightDataColumnCollection_CannotRemoveColumnFromReadOnlyCollection {
            get {
                return ResourceManager.GetString("LightDataColumnCollection_CannotRemoveColumnFromReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column already belongs to this collection, or to another collection..
        /// </summary>
        internal static string LightDataColumnCollection_ColumnAlreadyAdded {
            get {
                return ResourceManager.GetString("LightDataColumnCollection_ColumnAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection already has a column with the specified name. (The comparison is not case-sensitive.).
        /// </summary>
        internal static string LightDataColumnCollection_ColumnNameAlreadyExists {
            get {
                return ResourceManager.GetString("LightDataColumnCollection_ColumnNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection does not have a column at the specified index..
        /// </summary>
        internal static string LightDataColumnCollection_NoColumnByIndex {
            get {
                return ResourceManager.GetString("LightDataColumnCollection_NoColumnByIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection does not have a column with the specified name..
        /// </summary>
        internal static string LightDataColumnCollection_NoColumnByName {
            get {
                return ResourceManager.GetString("LightDataColumnCollection_NoColumnByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value array field count does not match table column count..
        /// </summary>
        internal static string LightDataRow_ArrayLengthInvalid {
            get {
                return ResourceManager.GetString("LightDataRow_ArrayLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cast type on null value..
        /// </summary>
        internal static string LightDataRow_CannotCastTypeOnNull {
            get {
                return ResourceManager.GetString("LightDataRow_CannotCastTypeOnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An edit tried to change the value of a read-only column..
        /// </summary>
        internal static string LightDataRow_CannotEditReadOnlyColumn {
            get {
                return ResourceManager.GetString("LightDataRow_CannotEditReadOnlyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column does not belong to this table..
        /// </summary>
        internal static string LightDataRow_ColumnDoesNotBelongToTable {
            get {
                return ResourceManager.GetString("LightDataRow_ColumnDoesNotBelongToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column specified by columnName cannot be found..
        /// </summary>
        internal static string LightDataRow_ColumnNotFoundByName {
            get {
                return ResourceManager.GetString("LightDataRow_ColumnNotFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column value is not in an appropriate format..
        /// </summary>
        internal static string LightDataRow_ColumnValueFormatInvalid {
            get {
                return ResourceManager.GetString("LightDataRow_ColumnValueFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column value is not a byte array..
        /// </summary>
        internal static string LightDataRow_ColumnValueIsNotByteArray {
            get {
                return ResourceManager.GetString("LightDataRow_ColumnValueIsNotByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an enumeration..
        /// </summary>
        internal static string LightDataRow_ColumnValueIsNotEnumeration {
            get {
                return ResourceManager.GetString("LightDataRow_ColumnValueIsNotEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data types of the value and the column do not match..
        /// </summary>
        internal static string LightDataRow_DataTypeMismatch {
            get {
                return ResourceManager.GetString("LightDataRow_DataTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum {0} value for string code {1} is not defined..
        /// </summary>
        internal static string LightDataRow_EnumStringValueInvalid {
            get {
                return ResourceManager.GetString("LightDataRow_EnumStringValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum {0} value for int code {1} is not defined..
        /// </summary>
        internal static string LightDataRow_EnumValueInvalid {
            get {
                return ResourceManager.GetString("LightDataRow_EnumValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader field count does not match table column count..
        /// </summary>
        internal static string LightDataRow_ReaderFieldCountInvalid {
            get {
                return ResourceManager.GetString("LightDataRow_ReaderFieldCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item data type {0} is invalid. Must have Clone method..
        /// </summary>
        internal static string LightDataRow_ReferenceTypeWithoutCloneMethod {
            get {
                return ResourceManager.GetString("LightDataRow_ReferenceTypeWithoutCloneMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent table has no columns..
        /// </summary>
        internal static string LightDataRow_TableHasNoColumns {
            get {
                return ResourceManager.GetString("LightDataRow_TableHasNoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index value {0} was out of row list range..
        /// </summary>
        internal static string LightDataRowCollection_IndexOutOfRowRange {
            get {
                return ResourceManager.GetString("LightDataRowCollection_IndexOutOfRowRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection does not have a row at the specified index..
        /// </summary>
        internal static string LightDataRowCollection_NoRowAtIndex {
            get {
                return ResourceManager.GetString("LightDataRowCollection_NoRowAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row was created for different table..
        /// </summary>
        internal static string LightDataRowCollection_RowBelongsToOtherTable {
            get {
                return ResourceManager.GetString("LightDataRowCollection_RowBelongsToOtherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source string contains no fields..
        /// </summary>
        internal static string NoFieldsInString {
            get {
                return ResourceManager.GetString("NoFieldsInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML file folder specified ({0}) contains no XML files..
        /// </summary>
        internal static string NoFilesInFolder {
            get {
                return ResourceManager.GetString("NoFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change database while a transaction is in progress..
        /// </summary>
        internal static string SqlAgentBase_CannotChangeDatabase {
            get {
                return ResourceManager.GetString("SqlAgentBase_CannotChangeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create database while transaction is in progress..
        /// </summary>
        internal static string SqlAgentBase_CannotCreateDatabase {
            get {
                return ResourceManager.GetString("SqlAgentBase_CannotCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start a new transaction while there is another transaction in progress..
        /// </summary>
        internal static string SqlAgentBase_CannotStartTransaction {
            get {
                return ResourceManager.GetString("SqlAgentBase_CannotStartTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new database....
        /// </summary>
        internal static string SqlAgentBase_CreatingCloneDatabase {
            get {
                return ResourceManager.GetString("SqlAgentBase_CreatingCloneDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name is not set..
        /// </summary>
        internal static string SqlAgentBase_CurrentDatabaseNull {
            get {
                return ResourceManager.GetString("SqlAgentBase_CurrentDatabaseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone has been canceled by the user..
        /// </summary>
        internal static string SqlAgentBase_DatabaseCloneCanceled {
            get {
                return ResourceManager.GetString("SqlAgentBase_DatabaseCloneCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone has been canceled by the user. WARNING. The target database has already been creted..
        /// </summary>
        internal static string SqlAgentBase_DatabaseCloneCanceledAfterCreate {
            get {
                return ResourceManager.GetString("SqlAgentBase_DatabaseCloneCanceledAfterCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone completed succesfuly..
        /// </summary>
        internal static string SqlAgentBase_DatabaseCloneCompleted {
            get {
                return ResourceManager.GetString("SqlAgentBase_DatabaseCloneCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching database schema....
        /// </summary>
        internal static string SqlAgentBase_FetchingDatabaseSchema {
            get {
                return ResourceManager.GetString("SqlAgentBase_FetchingDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge database schema is empty..
        /// </summary>
        internal static string SqlAgentBase_GaugeSchemaEmpty {
            get {
                return ResourceManager.GetString("SqlAgentBase_GaugeSchemaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction to commit..
        /// </summary>
        internal static string SqlAgentBase_NoTransactionToCommit {
            get {
                return ResourceManager.GetString("SqlAgentBase_NoTransactionToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction to rollback..
        /// </summary>
        internal static string SqlAgentBase_NoTransactionToRollback {
            get {
                return ResourceManager.GetString("SqlAgentBase_NoTransactionToRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file {0} due to duplicate query token {1}..
        /// </summary>
        internal static string SqlDictionary_DuplicateTokensInRepository {
            get {
                return ResourceManager.GetString("SqlDictionary_DuplicateTokensInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file {0} due to missing query tokens..
        /// </summary>
        internal static string SqlDictionary_NullTokensInRepository {
            get {
                return ResourceManager.GetString("SqlDictionary_NullTokensInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL agent does not implement repository file prefix..
        /// </summary>
        internal static string SqlDictionary_RepositoryFilePrefixNotImplemented {
            get {
                return ResourceManager.GetString("SqlDictionary_RepositoryFilePrefixNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository files found or they contain no data for the SQL agent type {0}..
        /// </summary>
        internal static string SqlDictionary_RepositoryFilesNotFound {
            get {
                return ResourceManager.GetString("SqlDictionary_RepositoryFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL repository path is not initialized..
        /// </summary>
        internal static string SqlDictionary_RepositoryPathNotInitialized {
            get {
                return ResourceManager.GetString("SqlDictionary_RepositoryPathNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL query token {0} is unknown..
        /// </summary>
        internal static string SqlDictionary_UnknownSqlQueryToken {
            get {
                return ResourceManager.GetString("SqlDictionary_UnknownSqlQueryToken", resourceCulture);
            }
        }
    }
}
