//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apskaita5.DAL.MySql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apskaita5.DAL.MySql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute batch while a transaction is in progress..
        /// </summary>
        internal static string CannotExecuteBatchException {
            get {
                return ResourceManager.GetString("CannotExecuteBatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a transaction while another transaction is in progress..
        /// </summary>
        internal static string CannotStartTransactionException {
            get {
                return ResourceManager.GetString("CannotStartTransactionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a database while a transaction is in progress..
        /// </summary>
        internal static string CreateDatabaseExceptionTransactionInProgress {
            get {
                return ResourceManager.GetString("CreateDatabaseExceptionTransactionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sql agent has no database specified..
        /// </summary>
        internal static string CurrentDatabaseNullException {
            get {
                return ResourceManager.GetString("CurrentDatabaseNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB schema for the mysql database {0} using engine {1}..
        /// </summary>
        internal static string DbSchemaDescription {
            get {
                return ResourceManager.GetString("DbSchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} field {1} schema and index definitions are obsolete..
        /// </summary>
        internal static string DbSchemaErrorFieldAndIndexObsolete {
            get {
                return ResourceManager.GetString("DbSchemaErrorFieldAndIndexObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} in table {1} missing..
        /// </summary>
        internal static string DbSchemaErrorFieldMissing {
            get {
                return ResourceManager.GetString("DbSchemaErrorFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} field {1} schema definition is obsolete..
        /// </summary>
        internal static string DbSchemaErrorFieldObsolete {
            get {
                return ResourceManager.GetString("DbSchemaErrorFieldObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} in table {1} is obsolete..
        /// </summary>
        internal static string DbSchemaErrorFieldRedundant {
            get {
                return ResourceManager.GetString("DbSchemaErrorFieldRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} field {1} index definition is obsolete..
        /// </summary>
        internal static string DbSchemaErrorIndexObsolete {
            get {
                return ResourceManager.GetString("DbSchemaErrorIndexObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} missing..
        /// </summary>
        internal static string DbSchemaErrorTableMissing {
            get {
                return ResourceManager.GetString("DbSchemaErrorTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} is obsolete..
        /// </summary>
        internal static string DbSchemaErrorTableObsolete {
            get {
                return ResourceManager.GetString("DbSchemaErrorTableObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disable foreign keys without a transaction..
        /// </summary>
        internal static string DisableForeignKeysExceptionTransactionNull {
            get {
                return ResourceManager.GetString("DisableForeignKeysExceptionTransactionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot drop database while transaction is in progress..
        /// </summary>
        internal static string DropDatabaseExceptionTransactionInProgress {
            get {
                return ResourceManager.GetString("DropDatabaseExceptionTransactionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value {0} is not implemented..
        /// </summary>
        internal static string EnumValueNotImplementedException {
            get {
                return ResourceManager.GetString("EnumValueNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields cannot be empty..
        /// </summary>
        internal static string FieldsEmptyException {
            get {
                return ResourceManager.GetString("FieldsEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get schema errors while a transaction is in progress..
        /// </summary>
        internal static string GetSchemaErrorsExceptionTransactionInProgress {
            get {
                return ResourceManager.GetString("GetSchemaErrorsExceptionTransactionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is not set, cannot get schema..
        /// </summary>
        internal static string GetSchemaExceptionNullDatabase {
            get {
                return ResourceManager.GetString("GetSchemaExceptionNullDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get schema while a transaction is in progress..
        /// </summary>
        internal static string GetSchemaExceptionTransactionInProgress {
            get {
                return ResourceManager.GetString("GetSchemaExceptionTransactionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare fields with diferent names..
        /// </summary>
        internal static string InvalidFieldComparisonException {
            get {
                return ResourceManager.GetString("InvalidFieldComparisonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not a valid MySql transaction..
        /// </summary>
        internal static string InvalidTransactionType {
            get {
                return ResourceManager.GetString("InvalidTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual rollback..
        /// </summary>
        internal static string ManualRollbackException {
            get {
                return ResourceManager.GetString("ManualRollbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql database data type {0} is unknown..
        /// </summary>
        internal static string NativeTypeUnknownException {
            get {
                return ResourceManager.GetString("NativeTypeUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception of type &apos;{0}&apos;, message: {1}.
        /// </summary>
        internal static string NonSqlExceptionDescription {
            get {
                return ResourceManager.GetString("NonSqlExceptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction to commit..
        /// </summary>
        internal static string NoTransactionToCommitException {
            get {
                return ResourceManager.GetString("NoTransactionToCommitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic parameter type {0} is not supported by MySqlAgent.ExecuteCommandInt..
        /// </summary>
        internal static string NotSupportedExecutionTypeException {
            get {
                return ResourceManager.GetString("NotSupportedExecutionTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query token cannot be empty..
        /// </summary>
        internal static string QueryTokenEmptyException {
            get {
                return ResourceManager.GetString("QueryTokenEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        internal static string SqlExceptionAccessDenied {
            get {
                return ResourceManager.GetString("SqlExceptionAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql server returned an exception: Code={0}; ErrorCode={1}; HResult={2}; Number={3}; SqlState={4}; Message=&apos;{5}&apos;.
        /// </summary>
        internal static string SqlExceptionMessage {
            get {
                return ResourceManager.GetString("SqlExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING. Critical SQL transaction error, failed to rollback the transaction.{6}MySql server returned an exception: Code={0}; ErrorCode={1}; HResult={2}; Number={3}; SqlState={4}; Message=&apos;{5}&apos;{6}Initial exception that caused the rollback:{6}{7}{6}SQL statement/query that caused the exception:{6}{8}.
        /// </summary>
        internal static string SqlExceptionMessageRollbackFailed {
            get {
                return ResourceManager.GetString("SqlExceptionMessageRollbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql server returned an exception: Code={0}; ErrorCode={1}; HResult={2}; Number={3}; SqlState={4}; Message=&apos;{5}&apos;{6}SQL statement/query that caused the exception:{6}{7}.
        /// </summary>
        internal static string SqlExceptionMessageWithStatement {
            get {
                return ResourceManager.GetString("SqlExceptionMessageWithStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the MySql server. Server is down, host address is invalid or connection is blocked by a firewall..
        /// </summary>
        internal static string SqlExceptionUnableToConnect {
            get {
                return ResourceManager.GetString("SqlExceptionUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception occured while opening connection to the MySql server: {0}.
        /// </summary>
        internal static string SqlExceptionUnknownException {
            get {
                return ResourceManager.GetString("SqlExceptionUnknownException", resourceCulture);
            }
        }
    }
}
